:- module(tests, [resolve_tests/5, prove_tests/4]).

% definiujemy operatory ~/1 oraz v/2
:- op(200, fx, ~).
:- op(500, xfy, v).

% Zbiór faktów definiujących testy dla predykatu resolve
resolve_tests(single_test, p, p v r, ~p v q, r v q).
resolve_tests(single_left, p, p, ~p v p, p).
resolve_tests(single_right, p, p v q, ~p, q).
resolve_tests(excluded_middle, p, p v q, ~q v ~p, q v ~q).
resolve_tests(excluded_middle_ext, p, p v ~p, ~p v p, p v ~p).
resolve_tests(contradiction, p, p, ~p, []).
resolve_tests(contradiction_ext, p, p v p v p v p v p, ~p v ~p v ~p, []).
resolve_tests(repeat_var, p, p v q v p v q v ~p, ~p v q v ~p, q v ~p).
resolve_tests(trickly, q, p v s v t v q, ~t v r v ~q v u , p v s v t v ~t v r v u).

% Zbiór faktów definiujących testy poprawnościowe dla predykatu prove
prove_tests(excluded_middle, validity, [p v ~p], sat).
prove_tests(only_negative, validity,[~p v ~q],sat).
prove_tests(only_positive, validity,[p v q],sat).
prove_tests(empty, validity, [], sat).
prove_tests(clause_empty, validity, [q,[],p], unsat).
prove_tests(simple_test, validity,[p v q, ~p v ~q],sat).
prove_tests(many_prove, validity, [~p, r, p v q v ~r, p v ~q v r, ~r],unsat).
prove_tests(no_linear, validity, [~p v q, p v q, ~p v ~q, p v ~q], unsat).
prove_tests(single_positive, validity, [p v q, ~p v r, ~q v r, r v r],sat).
prove_tests(single_negative, validity, [p v q v p, ~p v r v ~p, ~q v r, ~r v ~r],unsat).
prove_tests(unnecessary, validity, [p v q v r, ~p v q, r v ~q, p , ~q],unsat).
prove_tests(going, validity, [~p v q, ~q v r, ~r v t, ~t v p, p, ~t],unsat).
prove_tests(loop_0, validity, [~p v ~g v ~p, ~p v q v q, ~p v ~t v ~p, p v g v p, p v ~p, ~p v ~s, 
~g v ~t, ~q v q, ~g v ~s, t v s, ~t v ~s], unsat).
prove_tests(loop_1, validity, [~s, ~q v ~r, p v ~s, s v ~p],sat).
prove_tests(loop_2, validity, [~r v ~p v ~s, r v ~q, ~p v ~r v q], sat).
prove_tests(loop_3, validity, [~r v ~p v ~s, r v ~q, ~p v ~r v q, q v p v s], sat).

prove_tests(trickly_1, validity, [p v q v ~p, ~r, ~t v p v r, ~r v g v ~t, g v ~q v r, q v ~q v t],sat).
prove_tests(trickly_2, validity, [~p v q, ~q v r, ~r v p, p v q v r, ~p v ~q v ~r],unsat).

prove_tests(books_1, validity, [~p v q, ~q v s, ~s v p, p v q v s, ~p v ~q v ~s], unsat).
prove_tests(books_2, validity,[q v ~q, ~p v ~q, ~q v p v q, ~p v ~q, ~q v ~s v s, ~s v ~p, s v q v ~p, 
~s v q, s v p, s, ~p v ~q v s , p v ~q],unsat).	

prove_tests(long, validity, [~q v ~p , p v ~t v ~s , ~s , s v ~p v p , ~q v s v ~t , ~t v ~p , 
~q v ~s v q , s v ~q , s v t v ~t , s v t v p , q v ~p v s , ~t v q , q v ~t , ~q v q v ~s , 
t v ~p v ~q , ~s v s v ~q], unsat).

prove_tests(mp, validity, [
x19, ~x18 v x19, ~x15 v x19, x15 v x18 v ~x19, ~x16 v ~x17 v ~x18, ~x16 v x17 v x18, 
x16 v ~x17 v x18, x16 v x17 v ~x18, ~x02 v ~x01 v ~x17, ~x02 v x01 v x17, 
x02 v ~x01 v x17, x02 v x01 v ~x17, ~x02 v ~x01 v ~x16, ~x02 v x01 v x16, 
x02 v ~x01 v x16, x02 v x01 v ~x16, ~x13 v ~x14 v ~x15, ~x13 v x14 v x15, 
x13 v ~x14 v x15, x13 v x14 v ~x15, ~x02 v ~x01 v x14, x01 v ~x14, x02 v ~x14, 
~x02 v ~x01 v x13, x01 v ~x13, x02 v ~x13 
],unsat).

% Zbiór faktów definiujących testy wydajnościowe dla predykatu prove
prove_tests(hard, performance, [
~hs v hs v ppp , sm v qp v ms , hp v gt v ~mc , qu v ~gc v su , ~ug v ~us v gt , ~pp v ~gg v g , 
up v ~hh,p v ug v ~pq , hg v hh v ~mm , cg v ~ss v tu , ~pt v ~tt v tg , hs v pc v ~h , 
~hh v ts v h , cg v um v ~uu , ~m v ph v ~qp , mp v uh v ppp , mm v ~mc v tm , ~qm v qp v ~gm , 
qg v ~su v tg , hq v ug v mp , cu v ~pc v ~gc , gt v ~cp v uc , uq v q v qp , cc v ps v ug , 
pg v cq v ~pp , ms v ~qq v g , pp v hq v ~qs , tu v ~qh v ~mh ,pm v ~h v ~mc , ~hq v tm v ~pg , 
qq v ~ch v ~ps , ch v ~tt v ~c , ~mp v mm v ~sp , s v ~qg v mu , u v ~tq v up , uh v ~u v hg , 
tc v ss v ~q , ~qp v ~u v mg , ~mg v sm v hp , ~qm v mt v ph , ~tp v qc v ~q , ~mu v um v ~cs , 
~gs v mh v qs , mp v ct v mt , m v ~mp v pt , sq v ~sh v mh , tq v ~cs v ~c , ~mp v sp v ~ct , 
sc v ~us v ~ms , ~pq v cq v c , ~cc v hp v ~pc , ~q v ~mm v pp , hg v ~cq v ~gp , ~c v uc v ~cp , 
~tc v tu v ~uu , ~mh v gs v sc , ~sg v ~ch v h , ~mh v hm v s , ~pt v ~sp v qp , st v up v ~mh , 
cu v pm v ~q , hg v gh v sm , hp v pc v ~sh , ~qm v pq v ps , qh v cm v ~mg , ~gc v hs v ~hp , 
cs v cg v hs , ~ppp v tq v sc , gc v mu v ~sg , hh v ~mu,~pg v gu v mu , tt v hp v ~gm , 
ug v qh v ~tp , u v cc v qp , cu v ~pq v ~mm , ~qh v ~ht v hm , pp v ~um v ~ht , ~tq v ~qc v hc , 
cc v qh v p , ~q v sm v ~u , tq v sp v up , ~tg v hs v ~h , ~cp v mt v ~ph , ~qu v t v ~th , 
gt v g v ~mg , qh v up v sq , th v us v ~up , ~cc v qp v ~cp , ~ts v su v ~uh , us v hh v qp ,
~p v q v ~s v t v u ,~p v q v ~s v t v ~u , ~p v q v ~s v ~t v u , ~p v q v ~s v ~t v ~u , 
~p v ~q v s v t v u , ~p v ~q v s v t v ~u , ~p v ~q v s v ~t v u , ~p v ~q v s v ~t v ~u , 
~p v ~q v ~s v t v u , ~p v ~q v ~s v t v ~u , ~p v ~q v ~s v ~t v u , ~p v ~q v ~s v t v ~u,
mu, ~ut v ppp v ~cm , th v gh v gm , gp v ~tp v ~g , sm v sp v ~st , ~qs v ~us v hg , mu v sp v hg , 
~qq v mc v ~qg , st v ut v qq , ts v ~qt v uc , cu v ~th v ~gs , ~tg v cm v ~mu , sc v cq v ~cp , 
mp v ~pp v ~qp , gm v ~mc v sc , hq v ~pp v ss , ~tg v ~gh v ch , ~cu v ~uc v gp , pu v ms v ~mp , 
~ts v mt v ~pg , ~qg v qs v ph , ~qh v um v tt , mc v pm v qp , ~qs v sm v ~qc , g v hs v ut , 
~tq v uq v ~c , gp v t v ~hh , tt v qt v hp , ~ch v ~sh v hg , ~sp v cs v ~mq , ~cg v pp v ~hq , 
ph v ~qu v ~hc , p v ~up v ~ms , ~hp v ug v q , qg v ~sm v cu , hm v ~ch v ~su , sp v ~qg v ~mu , 
ts v ~cg v mm , um v gp v ~cg , tg v mc v qg , ~tm v qs v ~sc , ph v ~hg v ~qs , gg v cu v ~qt , 
mt v ~pp v ~hq , ~ct v ps v p , cp v um v ~pu , ~qh v mg v t , ~gc v st v ~pq , ~tt v ~tm v qc , 
~pq v ~gp v tq , ~mu v pu v ~qt , qg v ~gu v ~gm , ~pp v ~ph v ch , qg v ~cq v ~t , t v ~th v ~qs , 
st v ms v ~cs , cm v ~t v sc , ~mp v su v ~qh , ~mq v ~tq v us , pq v ~mc v ~mq , ~tc v st v ~m , 
u v ~h v ~hu , su v up v ~ug , uc v uq v ~cp , cs v cp v ~us , ~gu v mc v ~mm , up v ~mp v ~cu , 
h v tp v up , gu v ~tu v qc , ~gu v pc v cs , ~gp v pt v ~hu ,gh v ~mc v ~mp , pu v u v mq , 
hu v ~cq v ~pu , ug v ~gu v cp , ~hp v gg v sh , uq v ~uh v ~cu , mt v ~su v cm , ~tt v sc v ~th , 
sm v ~sp v ~qs , ph v ~hm v ~th , mu v ~hp v ~tt , tp v up v mp , ~mc v ug v ~uc , ~cp v mp v c , 
qq v hc v mg , tm v ~pp v uh , h v ~cm v qu , mu v ~ph v ~pt , us v ~p v ch , pp v ~hu v ~t , 
~mc v ~pu v sm , ~cm v pt v qh , ~sg v ~mt v qu , uh v cg v hg , ph v ~uq v ct , ~ts v ug v pp , 
ts v hq v ~uc , pc v ~mp v sq , ~uu v ~uc v cu , us v gq v pu , hm v mp v ~qt , ug v ts v uc , 
~tt v ~gu v tu , ~sh v ~sc v cp , ~u v cg v ~ut , hc v ~u v ~uu , ~ht v mh v ~cm , qc v ~su v mp , 
~qt v um v sp , tc v ~qp v ~cp , ~hc v ~mh v mm , ~g v qq v ~mm , ut v gc v u , ch v ts v gp , 
~hc v qg v gg , ~ch v pc v ~gp , hq v uc v cm , ~hu v ~th v sc , ug v cp v ~qp , ~gq v ~hm v qt , 
qs v ~tu v ~pp , ~gs v ~hm v pu , hh v hp v tu , qu v ~ms v t , sh v ~sm v qp , ~hc v sh v ~sm , 
cg v tp v qp , qc v qq v ~pm , ~pp v q v mh , mm v ~mc v ~hg , ~cq v ~ph v mu , gm v ~qu v gt , 
~sc v ph v st , qs v ct v uc , qs v ut v ~th , cp v ~mq v tp , mc v qc v ~t , hg v up v pp , 
~qq v mp v tm , pq v g v ~ut , tt v qp v us ,pp v ~tg v ~uq , ~cm v mc v ~pp , hp v ~gq v ~gp , 
hg v sh v sp , ~pg v hp v ~hp , ~cs v sq v ~sc , mc v pu v ~qp , ~u v t v ~st , tc v ~c v ~ss , 
hs v ~uu v qg , up v ~cu v uq , ~gu v qp v hq , ts v mg v uu , ~mm v ~qp v p , pg v ~qm v ~gh , 
gp v ~ms v ~qs , ~gm v ug v ~tu , q v ~qq v tm , sg v ~ppp v q , hu v ~uu v ~gp , t v ~su v ~hc , 
~s v ~up v sh , ~q v mq v ~tu , qm v ~tu v ~mg , uq v ~q v ~cs , pm v gp v ht , qg v ~ss v sp , 
~hm v ~pm v sq , ct v ~tu v ~sg , ~t v pu v ~q , ~gp v ~uq v q , q v sp , sh v ppp v tp , 
~sp v pt v sh , h v ~sp v hp , ~gp v ~gg v tg , gp v up v ~ts , qh v ~qt v ~hs , ch v ~ct v ~sm , 
qc v ~uq v ~qh , tm v qt v ~ht , ug v hp v ~pt , ~sg v cp v ~pg , pm v ~t v cp , pu v ~mg v qg , 
cq v qh v cm , ~cg v mp v ~mh , ~h v ~mu v mh  ,~up v pg v ~ch , ~hg v s v ~pp , ~up v us v hc , 
m v ~hc v ~hp , sq v m , up v tc , ~pq v ~mp v g , ~pp v sg v gs , sh v ~s v ~tq , u v ~tc v mg , 
sm v ~ts v ~hm , cq v q v ~mm , ~c v tp v mc , pg v ~tp v gm , uu v hm v ~pp , hu v ~gt v gp , 
~pq v cp v mp , sc v mu v ~gc , ~hs v ~mc v pg , ct v qh v sm , hp v ~ut v qh , pt v ~cm v ~qt , 
p v q v s v t v u , p v q v s v t v ~u , p v q v s v ~t v u , p v q v s v ~t v ~u , 
p v q v ~s v t v u , p v q v ~s v t v ~u , p v q v ~s v ~t v u , p v q v ~s v ~t v ~u , 
~uh v qq v cp , ~qc v g v ~uu , ~gc v ~ut v tu , mg v ~mu v ~hp , ~cc v ~st v ss , ~m v gt v ~cg , 
~cg v ~um v mc , ~hu v up v cq , hm v ms v pm , sp v uc v ~hp , ~uc v ~qq v uh , ts v hu v hp , 
~cp v tu v tp , qp v ~mp v ~qp , ~hm v cc v ct , ~qm v mm v ~ss , ~st v ~p v pm , qp v c v ~pp , 
~pt v qm v gu , qc v gq v ~cu , ~tm v gh v qc , pu v ~gm v ~sh , pp v ~up v qp , sp v pp v qu , 
~qg v qc v ~cs , hs v ~ms v ~ps , ppp v ~mm v ~q , s v gp v ss , ~ut v cs v ~c , ~mg v qg v ~mm , 
~uu v u v ~qc , cp v ~pu v ph , uh v uc v ~ts , mt v ~qu v sp , ~pp v ~up v hp , s v qq v hh , 
cp v ~uu v ~ch , pu v qu v s , up v hp , tg v u v cs , pc v ~sg v ~tc , ~gp v ~mg v sg , 
~ph v mt v ~tp , pp v ~us v ts , ~hh v ~p v gp , ht v ~pc v ~sc , ~tc v sh v ~cp , pu v ht v uu , 
~mh v tp v c , tp v gs v hp , um v m v gg , ~us v ~hg v gg ,~cp v pp v gu , ~qh v ~mc v hp , 
~cc v uq v ~qg , tm v ~sg v m , ~hp v cs v ~ug , cu v ppp v ~ht , sp v ~ph v sq , cc v ~th v ~g ,
p v ~q v s v t v u , p v ~q v s v t v ~u , p v ~q v s v ~t v u , p v ~q v s v ~t v ~u , 
p v ~q v ~s v t v u , p v ~q v ~s v t v ~u , p v ~q v ~s v ~t v u , p v ~q v ~s v ~t v ~u , 
~p v q v s v t v u , ~p v q v s v t v ~u , ~p v q v s v ~t v u , ~p v q v s v ~t v ~u ,
cp v ss v qu , mp v ts v hc , ~gu v ~hp v hq , sp v tp v hh , ppp v qp v ~pp , ps v sp v qu , 
us v qu v ~qt , h v mu v ~hm , sc v qs v ~ct , hq v ~ug v ~gp , p v ~h v tp , ~gs v qp v uu , 
~ts v hq v sq , qp v q v ~cq , hq v uu v ~q , ~ut v ~mq v st , ~us v hh v ~qc , ~m v ~hm v ct , 
~sp v ~hg v m , qu v qc v um , ~p v gs v ~sq , ~tm v mu v ~m , ~ug v ~gm v gp , ~t v cc v hs , 
p v pg v ~ht , pg v qm v p , h v h,~qq v qu v ~su , mh v ~qu v ~ct , ps v ~gs v ~mp , ~gu v ~ss v q , 
~pc v ~sg v ts , gs v ~q v ~ts , ~tg v cu v ~ss , ~h v ~up , cq v ~hs v ~ms , qq v th v ms , 
u v mt v pq , ~mt v p v ~ms , ~tm v p v tp , ~qg v ~cs v ms , ~tc v mh v ~tm 
],unsat).

prove_tests(unnecessary_variables, performance, [
oo v g v or , h v e v ou , m v w v e , w v c v or , w v oe , h v on v h , w v h v on , ou v w v w , 
g v r v w , or v oo v on , e v o , e v oe v oo , on v u v w ,g v r v u , c v g v h , oo v ow , 
oe v m v o , r v h v w , m v ou v m , r v o v oo , c v m , w v g v ou , e v oo v r , c v or v oe , 
g v m v oe , m v r v ou , u v h v g , o v w v ou , e v e , on v u v oe , r v ow , oe v or , oo v ou v c , 
c v ow v oe , or v o v c , ow v u v r , or v oe v u , w v e , ~t v ~p , p v s v t , ~q v s v ~p , 
q v s v ~q , p v ~t v t , ~q v t v ~t , t v s , q v t , ~q v t v ~p , p v ~t v t , ~t v s v ~q , 
~t v p , p , p v ~s v q , q v ~p , s v p v ~t,u v r v m , o v c v g , oe v or v oo , e v w v ow , 
g v r v w , or v r v h , ow v on v w , g v o v oo , g v e , w v r v ou , or v ow v c , e v c v or , 
m v c , u v m v o , c v w v ow , ou v g v oo , ou v oo v r , oe v g , on v h v oo , ow v w v g , 
o v h v c , oo v e v w, ip v h v hp , ht v hw v i , pw v oh v hw , io v oo v ux , pq v pi v oo , 
ho v pt v hx , w v ix v i , iu v it v iw , hx v ho v oq , ip v ow v o , pu v hw v ot , ip v hi v ih , 
or v po v u , pr v pw v oq , iq v q v r , iw v pu v u , ir v ox v p , ph v ow v it , ii v hi v hr , 
po v u v oi ,hr v ht v oq , hi v pi v iq , hr v p v pu , pq v pq v w , ux v hw v hh , pi v i v ho , 
hp v i v io , pu v h , ih v ir v hp , ix v pq v pu , p v pw v ot , iw v hp v hq ,io v q v hp , 
hq v iu v ii , it v h v io , ox v pt v oh , pw v oh v iq , ox v it v pt , oo v hp v po ,r v ii v iw ,
ow v pi v io , o v od v pr , pq v po v pt , hp v t v iu , po v it v oh , o v ir v ph , 
ht v ix v ht , hx v hi v ot , w v ow v pq , t v iq v q , ot v t v iq , or v i v hh , io v oi v or , 
oq v hw v oo , pq v ou v pq , oi v pp v u , oo v hx v pq , hh v hx v pu , t v pw v oh , oi v q v u ,
pi v it v ot , h v ix v px , pr v ow v ip , pp v p v iu , ow v ph v u , pu v hu v px , oq v or v ux , 
i v ou v ir , ux v ir v ho , p v ih v hh , hp v hh v hu , ux v t v it , ph v oq v ow , u v hq v oi , 
ot v r v ir , h v i v pq , or v u v pu , hx v px v ip , pt v hq , pr v t v hu , oi v r v o , 
hh v oi v pr , ir v hr v r , hp v t v ho , rp v u v ux , hp v iu v oi , w v oq v hu , ih v ux v pq , 
ux v ou v pp , ih v q v hw , q v or v q , pt v oi v hi , po v it v w , ii v hr v hr , po v ox v w , 
ox v io v ii , ii v pr v ih , u v pw v or , hq v hq v oo , ot v q v ux , p v iw , w v u v hi , 
or v pq v hi ,ih v hx v hh , ht v io v i , ph v hi v oi , pu v ih v po , or v ih v po , pt v h v t , 
h v or v hw , ht v pq v hi , hw v pp v q , iq v pw v pi , w v o v i , h v hh v q , hq v oo v iq , 
r v oi v pq , r v hu v hi , iu v hx v pw , ho v iu v hp ,hp v oi v pp , ot v ow v p , hh v hx v ii , 
ip v hh v r , pr v ix v o , t v ou v o , u v pi v hr , hw v hr v hx , po v pi v i , ot v ir v ho , 
iu v pw v hh , u v oa v hh , it v pp v hx , oo v pq v ii , ii v oq v po , h v ho v ir , iq v hh v oh , 
iu v iu v r , ix v ou v o , pu v ir v hp , hq v hq v ho , t v oh v or , hi v hp v iu , iw v ho v ip ,
ir v hp v hr , ux v pi v pt , ox v t v ux , io v pt v ip , hh v it v or , iu v io v hw , hw v px v ip , 
ow v w v iw , ir v ih v or , i v ho v ux , pq v ot v ou , hw v ot v pt , p v w v hi , or v or v ho , 
pp v pp v pt , oq v hh v ip , io v t v hw , ho v ix v ht , oh v hh v or , u v hu v r , hh v h v iw , 
ou v it v hh , oh v pr v ix , h v pw v p , pr v r v hr , h v h v p , pu v po v iw , pw v ih v ix , 
hp v ow v ht , hu v px v i , ho v pi v r , pp v ir v ip , oo v iw v oq , hp v or v hr , 
io v hq v ph , ow v oq v hr , iw v ou v oh , ow v ii v rp , pr v ix v u , hh v hi v iu , 
pp v ht v ot , ih v it v q , px v po v ii , ho v pw v ix ,ou v iu v oq , hp v oo v iu , 
ht v ip v ux , h v ip v or , oi v pi v hu , iu v p v ii , ii v oq v pq , oo v pp , pu v hh v or , 
oh v ou v ow , o v ih v hq , po v oq v po
],unsat).


prove_tests(subsets, performance, [ 
p v ~q v ~s , p v q v s v t v u v g v h v c v m v pp v pp v pq v ps v pt v pu , 
p v q v s v t v u v g v h v c v m v pp v pp v pq v ps v pt v ~pu , 
p v q v s v t v u v g v h v c v m v pp v pp v pq v ps v ~pt v pu , 
p v q v s v t v u v g v h v c v m v pp v pp v pq v ps v ~pt v ~pu , 
p v q v s v t v u v g v h v c v ~m v pp v pp v pq v ~ps v pt v pu ,  
p v q v s v t v u v g v h v c v ~m v pp v pp v pq v ~ps v pt v ~pu , 
p v q v s v t v u v g v h v c v ~m v pp v pp v pq v ~ps v ~pt v pu , 
p v q v s v t v u v g v h v ~c v ~m v ~pp v pp v pq v ps v pt v ~pu , 
p v q v s v t v u v g v ~h v c v ~m v pp v ~pp v ~pq v ps v pt v pu , p v q v s ,
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ps v pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ps v ~pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ps v ~pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ~ps v pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ~ps v pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ~ps v ~pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v pq v ~ps v ~pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ps v pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ps v pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ps v ~pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ps v ~pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v pt v ~pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v ~pt v pu ,~p v q v ~s ,  
p v q v s v t v u v g v ~h v c v ~m v pp v ~pp v ~pq v ps v pt v ~pu , 
p v q v s v t v u v g v ~h v c v ~m v pp v ~pp v ~pq v ps v ~pt v pu , 
p v q v s v t v u v g v ~h v c v ~m v pp v ~pp v ~pq v ps v ~pt v ~pu , 
p v q v s v t v u v g v ~h v c v ~m v pp v ~pp v ~pq v ~ps v pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v pq v ~ps v pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v pq v ~ps v pt v ~pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v pq v ~ps v ~pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v pq v ~ps v ~pt v ~pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ps v pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ps v pt v ~pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ps v ~pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ps v ~pt v ~pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v pt v ~pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v ~pt v pu , 
~p v q v s v t v ~u v g v h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v ~pt v ~pu , 
~p v q v s v t v ~u v g v ~h v c v m v pp v pp v pq v ps v pt v pu , 
~p v q v s v t v ~u v g v ~h v c v m v pp v pp v pq v ps v pt v ~pu , 
~p v q v s v t v ~u v g v ~h v c v m v pp v pp v pq v ps v ~pt v pu , 
~p v q v s v t v ~u v g v ~h v c v m v pp v pp v pq v ps v ~pt v ~pu , 
p v q v s v t v u v g v ~h v c v ~m v ~pp v ~pp v pq v ~ps v pt v ~pu , 
p v q v s v t v u v g v ~h v c v ~m v ~pp v ~pp v pq v ~ps v ~pt v pu , 
p v q v s v t v u v g v ~h v c v ~m v ~pp v ~pp v pq v ~ps v ~pt v ~pu , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ps v pt v pu , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ps v pt v ~pu , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ps v ~pt v pu , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ps v ~pt v ~pu ,~p v ~q v ~s , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ~ps v pt v pu , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ~ps v pt v ~pu , 
p v q v s v t v u v g v ~h v ~c v m v pp v ~pp v ~pq v ~ps v ~pt v pu , ~p v ~q v s , 
p v q v s v t v u v g v ~h v ~c v m v ~pp v pp v ~pq v ~ps v pt v ~pu , 
p v q v s v t v u v g v ~h v ~c v m v ~pp v pp v ~pq v ~ps v ~pt v pu , 
p v q v s v t v u v g v ~h v ~c v m v ~pp v ~pp v ~pq v ~ps v pt v pu , 
p v q v s v t v u v ~g v h v ~c v m v pp v pp v pq v ~ps v ~pt v pu , ~p v q v s , 
p v q v s v t v u v ~g v h v ~c v m v pp v pp v pq v ~ps v ~pt v ~pu , 
p v q v s v t v u v ~g v h v ~c v m v pp v pp v ~pq v ps v pt v pu , 
p v q v s v t v u v ~g v h v ~c v m v pp v ~pp v pq v ps v ~pt v pu , p v q v ~s , p v ~q v s ,
p v q v s v t v u v ~g v h v ~c v m v pp v ~pp v pq v ps v ~pt v ~pu , 
p v q v s v t v u v ~g v h v ~c v m v pp v ~pp v pq v ~ps v pt v pu , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp v ~pp v ~pq v ~ps v ~pt v ~pu ,~p
],unsat).

prove_tests(more_variables, performance, [
pt v g v ~ps , ~t v ~po v s , w v po v ~pp , pq v g v po , pq v q v ps , r v ~s v s , p v ~p v p , 
p v ~pq v w , p v ~ps , ~po v ~t v pt , ~g v pt v ps , q v ~pq v p , w v ~t v ~p , pt v po v pq , 
~pp v s , p v w v ~s , ps v q v ~s , ~pq v ~q , ~pp v ~r v pt , q v ps v ~g , pq v ~pt , s v ~p v pq , 
~ps v ~s v pt , q v ~s v p , t v ~s v ~q , ~p v ~g v ~pq , ~t v ~po v ~r , pp v po v ~t , 
~p v ~ps v ~ps , r v s v t , q v ~po v ps , ps v po v ps , p v ~w v ps , po v ~po v ~s , pt v ~ps , 
ps v t v ~pq , p v ~pt v r , ~w v s v g , po v ~p v ~s , s v ~r v pt , po v w v pq , g v pp v t , 
~pp v ~s v g , ~pt v ~po v g , ~r v pq v w , pq v ~s v ~ps , ~pq v ps v ~po , ~w v ~s v ps , 
~t v t v pq , ~t v ~q v ~ps , ~pq v p v ~po , p v ~ps v ~ps , ~ps v ~po v w , ~g v ~pp v p , 
~t v p v ps , ~ps v p v ~t , s v p v ps , ~ps v ps v ~p , pt v ~po , q v w v ps 
],unsat).

prove_tests(short_clauses, performance, [
~pp v qu , pp v ~pg , pu v c v pp , c v s v ~q , m v ~ps v ~qq , pg v ~g v ~qp , ~qt v h v ~h , 
~h v qs v ~qt , pg v qs v ~qu , pc v ~pq v ph , qu v ~p v pg , s v pp , g v ~t v ~p , t v pc v qs , 
c v ~c , m v pu v ~u , ~pu v pq v qp , pc v qp v qu , pp v ~qp v ~qs , ~h v t v ~q , ~pu v qu v pm , 
~s v c v ~u , ~h v qt v g , ~s v ~pq v ~pt , ~m v ~qu v pp , pp v ~pq v h , qs v ~p v qt , 
p v ~qt v ~q , ~pu v ~g v pg , ~qu v ~pt v h , pp v pm v ~u , ~pp v pc v pt , ~qq v ~qu v pc , 
ps v ~qu v ~g , m v g v ~q , pt v ~pg v ~pc , ~ph v ~qp v h , ~h v ~pp v ~pu , pu v ~pp v qp , 
q v pp v ~m , c v pq v g , ps v pu v ~qs , ~qp v ph v ~pg ,~q v ~c v pc , ~qs v qq v h ,
pp v ~pu v t , ~qu v ~pg v ~qs , qs v ~q v ~qp , g v ~pt v ~qp , pc v ~c v qt , ~m v qt v ~pq , 
m v ~pt v pc , pp v ~pp v ~m , ~pp v pg v ~pp , u v ~pq v qp , qu v ~u v pg , s v pp v ph , 
pg v ~qs v pp , qp v ~pm v ~u , ps v qp v ~h , ~pu v ~pm v ~qp , ~pg v h v pp , ps v pu v u , 
qp v pg v ~u , ~c v ~qp v ~h , ~qs v pq v ~qq , pc v ~qu v q , m v g , p v ~pu v ~ps , 
~pc v ps v s , h v m v ~pg , qq v ~qt v ~u , ~qp v g v ~pu , ~p v m v ~s , t v ~t v q , 
pp v ~pu v ~qu , pc v ~pq v pm , m v qq , ~pp v pp , qt v ~q , pq v qp v qs , ~m v ~qt v u , 
~pp v p v q , ~qq v ~pc v ~qs , ~pm v g v pc , qq v ~pm v ~pg , ~qs v pc v ~pu , ~qs v qs v u , 
qp v ~pm v ~t , ~pt v ~h v ~u , c v ~h v ~qu , ps v p v ~qp , t v qp v ~ps , ~qq v ~pg v pp , 
s v qu v ph , h v ~g v pu , ~m v ph v g , ~pq v qt v pm , qu v h v m , s v ~pm v pg
],unsat).


prove_tests(small_test, performance, [
~p v q v s v t v u v g v r v e v y v x v h v a v b v c v d v f v k,
p v ~q v s v t v u v g v r v e v y v x v h v a v b v c v d v f v k,
p v q v ~s v t v u v g v r v e v y v x v h v a v b v c v d v f v k,
p v q v s v ~t v u v g v r v e v y v x v h v a v b v c v d v f v k,
p v q v s v t v ~u v g v r v e v y v x v h v a v b v c v d v f v k,
p v q v s v t v u v ~g v r v e v y v x v h v a v b v c v d v f v k,
p v q v s v t v u v g v ~r v e v y v x v h v a v b v c v d v f v k,
p v q v s v t v u v g v r v ~e v y v x v h v a v b v c v d v f v k,
p v q v s v t v u v g v r v e v ~y v x v h v a v b v c v d v f v k,
p v q v s v t v u v g v r v e v y v ~x v h v a v b v c v d v f v k,
p v q v s v t v u v g v r v e v y v x v ~h v a v b v c v d v f v k,
p v q v s v t v u v g v r v e v y v x v h v ~a v b v c v d v f v k,
p v q v s v t v u v g v r v e v y v x v h v a v ~b v c v d v f v k,
p v q v s v t v u v g v r v e v y v x v h v a v b v ~c v d v f v k,
p v q v s v t v u v g v r v e v y v x v h v a v b v c v ~d v f v k,
p v q v s v t v u v g v r v e v y v x v h v a v b v c v d v ~f v k,
p v q v s v t v u v g v r v e v y v x v h v a v b v c v d v f v ~k,
~p v ~q v ~s v ~t v ~u v ~q v ~r v ~e v ~y v ~x v ~h v ~a v ~b v ~c v ~d v ~f v ~k, 
p v q v s v t v u v q v r v e v y v x v h v a v b v c v d v f v k
],sat).

prove_tests(bigger_test, performance, [
wq v ~t v sz v ~o v ur v ~z v ~pg , r v w v ~t v s v or , wq v ~t v s v ~o , r v ws v ~t v ~s v or , 
wr v ~t v s v ~o v ~u v z v pg , q v ~r v wg v t v ~s v ~o v u , qr v ~r v w v t v ~s v ~o v ~u , 
q v r v wr v t , q v r v w v ~t , ~w v t , q v ~r v wr v ~t v s v o v ur , 
q v r v w v ~t v s v ~o v ~u v z v ~pg , ~w v ~t v s v o v u v ~zr , ~q v r v ~wg , ~q v ~rg v w , 
~qg v ~r v ~w , q v ~r v ~w v ~t v s v o v ~u v z , 
w v t v ~s v ~o v ~u v z v pg v ~pp , ~q v ~r v w v t v ~s v ~o v ~u v z v ~pg v pp , 
~z v o , ~pp , ~q v ~r v w v t v ~s v o v ut v ~z v pg v pp , 
q v ~r v w v t v ~s v o v ur v ~z v pg v ~pp , ~r v ~t , pp v ~z , pp v t , 
~u v qp v ~q v ~r v ~w v t v ~s v o v ~u v ~z v pg v pp , 
~qr v ~r v ~wr v t v ~sr v o v ~ut v ~z v pg v ~pp , 
~qr v ~r v ~wr v t v ~s v o v ~u v ~z v ~pg v pp , ~q v ~r v ~w v tr v ~s v o v ~u v ~z v ~pg v ~pp , 
~qr v ~rr v ~w v t v ~sr v ~or v u v ~z v ~pg v pp , ~qr v ~r v ~w v ~t v s v o v ~u v z v ~pg v pp , 
~q v ~r v ~w v ~t v sr v o v ~u v z v ~pg v ~pp , qs v rs v w v t v rs v o v u v z v pg v pp , 
q v rq v w v t v s v o v u v z v pg v ~pp , qs v r v w v t v s v o v uq v z v ~pg v pp , 
q v r v w v t v s v o v u v z v ~pg v ~pp , qs v rs v w v t v sr v o v u v ~z v ~pg v ~pp , 
qg v r v w v t v s v o v ~uq v z v ~pg v ~pp , q v r v w v t v ~s v ~o v u v z v pg v ~pp , 
qs v rs v w v t v ~s v ~or v u v z v ~pg v pp , ~q v r v w , 
~q v r v ~w , ~q v ~r v w , q v r v w v t v ~s v ~o v u v ~z v ~pg v ~pp , 
qg v r v wr v tw v ~s v ~o v ~ut v z v pg v pp , pg v ~o v o , ~u v ~z v ~t , z v q v ~r , 
pp v pg v p , ~t v r v ~p , ~u v ~r v ~o , r v o v w , ~pg v s v pp , ~s v pp v s , ~t v ~z v w , 
~o v pg , pg v og v zg , ~s v ~o v o , q v p v ~pg , z v ~pp v o , 
pg v qg v rg v w v tg v s v o v us v z v pg v pp , pt v q v r v w v t v s v o v ug v z v pg v ~pp , 
p v qt v r v wg v t v s v o v ug v z v ~pg v pp , p v q v rt v wg v t v sg v o v u v z v ~pg v ~pp , 
p v q v r v w v tt v s v ot v ut v ~z v pg v pp , ~pg v pp v ~s , p v ~z , zt,
pp v q v r v zt v w v tp v s v o v u v z v pg v pp , 
p v qp v zt v r v w v t v st v o v u v z v pg v ~pp , 
p v q v r v w v zt v tp v s v o v u v z v ~pg v pp , 
qp v r v w v t v ~s v zt v ~o v ~u v z v pg v ~pp , ~o v ~u v zt v ~pg v zt v ~pp , 
q v r v w v t v ~s v zt v ~o v ~u v ~z v ~pg v ~pp , ~r v ~q , r v zt v t , ~o v zt v pg , 
pp v ~r v zt, ~q v r v w v t v zt v ~s ,q v r v wg v tg v ~s v ~o v ~u v zg v ~pg v pp , 
q v r v wg v t v ~s v ~o v ~u v pz v ~pg v ~pp , q v rt v w v t v ~s v ~po v ~pu v ~z v ~pg v ~pp ,
 ~r v ~q , r v t , ~zq v p v ~w v ~r v s v pt v ~o v ~u v ~z v qg v ~qq , 
~qs v p v ~w v ~r v s v t v ~o v ~u v ~z v ~qg v qq , 
~q v p v ~w v ~r v s v t v ~o v ~u v ~z v ~qg v ~qq , 
~q v p v ~w v ~r v sz v ~t v o v u v z v qg v qq , 
~qq v p v ~ws v ~r v s v ~t v o v u v z v qg v ~qq , 
~q v p v ~w v ~r v s v ~t v oq v pu v z v ~qg v qq , 
~wq v p v ~w v ~r v s v ~t v o v u v z v ~qg v ~qq , 
~q v p v ~w v ~r v s v ~t v o v u v ~pz v qg v qq , 
~q v p v ~w v ~r v s v ~t v o v u v ~z v qg v ~qq , 
~pq v p v ~w v ~r v s v ~t v o v pu v ~z v ~qg v qq , 
~q v p v ~w v ~r v s v ~t v o v up v ~z v ~qg v ~qq , 
~q v p v ~w v ~r v s v ~tp v o v ~u v z v qg v qq , 
~uq v pp v ~w v ~r v s v ~t v o v ~u v z v qg v ~qq , 
~q v p v ~w v ~r v s v ~t v o v ~u v z v ~qg v qq,
~o v pg , pp v ~r , ~q v r v w v t v ~s v o v u v ~z v ~pg v pp , 
w v t v ~s v o v u v ~z v ~pg v ~pp , ~q v ~r v w v t v s v o v ~u v z v pg v pp , ~r v ~q , 
tp v ~p , w v pg , q v sp , ~q v ~r v ~w v t v ~s v ~o v u , ~qt v ~r v ~w v t v ~s v ~o v ~u , 
~q v ~r v ~w v ~t v s v o v u , ~q v ~rt v ~w v ~t v s v ~o v u , ~q v ~r v ~w v ~t v s v ~o v ~u , 
~u v up , q v ~r v ~w v t v ~s , ~w v ~t v s , q v ~r v ~wt v ~t v ~s , 
q v ~r v ~w v ~t v s v o v ~u v ~z , r v w v ~t v s v ~o v ~u v z v ~pg , 
~q v r v w v ~t v s v o v ~u v ~z v pg , ~q v r v w v t v s v ~o v ~u v ~z v ~pg , 
r v w v ~t v ~s v o v u v z v pg , q v r v w v ~t v ~s v o v u v z v ~pg,~o v pg , p v q v s, 
~t v p v ~q, r v t, s v t, q v r, pp v ~r , 
~q v r v w v t v ~s v o v u v ~z v ~pg v pp , w v t v ~s v o v u v ~z v ~pg v ~pp,z v q v ~r , 
pp v pg v p , ~t v r v ~p , ~u v ~r v ~o , r v o v w , ~pg v s v pp, 
~uw v q v ~p v ~r v t v t v ~s v ~z v ~u v wg v ~ww , 
~wt v q v ~p v ~r v tz v tz v ~s v ~z v ~u v ~wg v ww , 
~w v q v ~p v ~qr v rt v t v ~ps v ~z v ~u v ~wg v ~ww , 
~w v qw v ~p v ~r v t v ~t v sz v z v u v wg v ww , 
~ww v qw v ~pt v ~r v t v ~t v s v z v wu v wg v ~ww , 
~w v q v ~p v ~r v t v ~tz v sw v z v u v ~wg v ww , 
~pw v qw v ~pt v ~r v t v ~tz v s v z v u v ~wg v ~ww , 
~wt v q v ~p v ~r v t v ~tz v s v z v ~u v wg v ww , 
~w v q v ~p v ~r v t v ~t v s v z v ~u v wg v ~ww ,
~qw v q v ~p v ~r v t v ~t v s v z v ~u v ~wg v ww , 
~w v qw v ~p v ~r v tr v ~t v s v z v ~uq v ~wg v ~ww , 
~w v qw v ~p v ~r v tz v ~tq v s v ~z v u v wg v ww ,
~zw v q v ~p v ~r v t v ~t v s v ~z v u v wg v ~ww , 
~wq v q v ~p v ~r v tw v ~t v s v ~z v u v ~wg v ww, 
~wq v u v ~z v ~s v t v r v ~p v ~g v ~w v qo v ~qq , 
~qt v u v ~zz v ~s v tz v r v ~p v ~g v ~w v ~qo v qq , 
~q v us v ~zs v ~us v st v r v ~zp v ~g v ~w v ~qo v ~qq ,
~q v u v ~z v ~s v t v ~rz v p v g v w v qo v qq ,
~qq v us v ~zt v ~s v t v ~r v p v g v qw v qo v ~qq , 
~qs v u v ~z v ~s v t v ~r v pq v g v w v ~qo v qq , 
~zq v uq v ~zt v ~s v t v ~r v p v g v w v ~qo v ~qq , 
~qt v u v ~z v ~s v t v ~rz v p v g v ~w v qo v qq , 
~q v u v ~z v ~s v tz v ~r v p v g v ~w v qo v ~qq , 
~uq v u v ~z v ~s v t v ~r v p v g v ~w v ~qo v qq , 
~q v us v ~z v ~s v ts v ~rz v p v g v ~wu v ~qo v ~qq , 
~q v u v ~z v ~s v t v ~ru v p v ~g v w v qo v qq , 
~gq v us v ~z v ~s v t v ~r v p v ~g v w v qo v ~qq , 
~qu v u v ~z v ~s v tq v ~r v p v ~g v w v ~qo v qq
],unsat).

prove_tests(biggest_test, performance, [
p v q v s v t v u v g v h v c v m v pp , p v q v s v t v u v g v h v c v m v ~pp , 
p v q v s v t v u v g v h v c v ~m v pp , p v q v s v t v u v g v h v c v ~m v ~pp , 
p v q v s v t v u v g v h v ~c v m v pp , p v q v s v t v u v g v h v ~c v m v ~pp , 
p v q v s v t v u v g v h v ~c v ~m v pp , p v q v s v t v u v g v h v ~c v ~m v ~pp , 
p v q v s v t v u v g v ~h v c v m v pp , p v q v s v t v u v g v ~h v c v m v ~pp , 
p v q v s v t v u v g v ~h v c v ~m v pp , p v q v s v t v u v g v ~h v c v ~m v ~pp , 
p v q v s v t v u v g v ~h v ~c v m v pp , p v q v s v t v u v g v ~h v ~c v m v ~pp , 
p v q v s v t v u v g v ~h v ~c v ~m v pp , p v q v s v t v u v g v ~h v ~c v ~m v ~pp , 
p v q v s v t v u v ~g v h v c v m v pp , p v q v s v t v u v ~g v h v c v m v ~pp , 
p v q v s v t v u v ~g v h v c v ~m v pp , p v q v s v t v u v ~g v h v c v ~m v ~pp , 
p v q v s v t v u v ~g v h v ~c v m v pp , p v q v s v t v u v ~g v h v ~c v m v ~pp , 
p v q v s v t v u v ~g v h v ~c v ~m v pp , p v q v s v t v u v ~g v h v ~c v ~m v ~pp , 
p v q v s v t v u v ~g v ~h v c v m v pp , p v q v s v t v u v ~g v ~h v c v m v ~pp , 
p v q v s v t v u v ~g v ~h v c v ~m v pp , p v q v s v t v u v ~g v ~h v c v ~m v ~pp , 
p v q v s v t v u v ~g v ~h v ~c v m v pp , p v q v s v t v u v ~g v ~h v ~c v m v ~pp , 
p v q v s v t v u v ~g v ~h v ~c v ~m v pp , p v q v s v t v u v ~g v ~h v ~c v ~m v ~pp , 
p v q v s v t v ~u v g v h v c v m v pp , p v q v s v t v ~u v g v h v c v m v ~pp , 
p v q v s v t v ~u v g v h v c v ~m v pp , p v q v s v t v ~u v g v h v c v ~m v ~pp , 
p v q v s v t v ~u v g v h v ~c v m v pp , p v q v s v t v ~u v g v h v ~c v m v ~pp , 
p v q v s v t v ~u v g v h v ~c v ~m v pp , p v q v s v t v ~u v g v h v ~c v ~m v ~pp , 
p v q v s v t v ~u v g v ~h v c v m v pp , p v q v s v t v ~u v g v ~h v c v m v ~pp , 
p v q v s v t v ~u v g v ~h v c v ~m v pp , p v q v s v t v ~u v g v ~h v c v ~m v ~pp , 
p v q v s v t v ~u v g v ~h v ~c v m v pp , p v q v s v t v ~u v g v ~h v ~c v m v ~pp , 
p v q v s v t v ~u v g v ~h v ~c v ~m v pp , p v q v s v t v ~u v g v ~h v ~c v ~m v ~pp , 
p v q v s v t v ~u v ~g v h v c v m v pp , p v q v s v t v ~u v ~g v h v c v m v ~pp , 
p v q v s v t v ~u v ~g v h v c v ~m v pp , p v q v s v t v ~u v ~g v h v c v ~m v ~pp ,
p v q v s v t v ~u v ~g v h v ~c v m v pp , p v q v s v t v ~u v ~g v h v ~c v m v ~pp , 
p v q v s v t v ~u v ~g v h v ~c v ~m v pp , p v q v s v t v ~u v ~g v h v ~c v ~m v ~pp , 
p v q v s v t v ~u v ~g v ~h v c v m v pp , p v q v s v t v ~u v ~g v ~h v c v m v ~pp , 
p v q v s v t v ~u v ~g v ~h v c v ~m v pp , p v q v s v t v ~u v ~g v ~h v c v ~m v ~pp , 
p v q v s v t v ~u v ~g v ~h v ~c v m v pp , p v q v s v t v ~u v ~g v ~h v ~c v m v ~pp , 
p v q v s v t v ~u v ~g v ~h v ~c v ~m v pp , p v q v s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
p v q v s v ~t v u v g v h v c v m v pp , p v q v s v ~t v u v g v h v c v m v ~pp , 
p v q v s v ~t v u v g v h v c v ~m v pp , p v q v s v ~t v u v g v h v c v ~m v ~pp , 
p v q v s v ~t v u v g v h v ~c v m v pp , p v q v s v ~t v u v g v h v ~c v m v ~pp , 
p v q v s v ~t v u v g v h v ~c v ~m v pp , p v q v s v ~t v u v g v h v ~c v ~m v ~pp , 
p v q v s v ~t v u v g v ~h v c v m v pp , p v q v s v ~t v u v g v ~h v c v m v ~pp , 
p v q v s v ~t v u v g v ~h v c v ~m v pp , p v q v s v ~t v u v g v ~h v c v ~m v ~pp , 
p v q v s v ~t v u v g v ~h v ~c v m v pp , p v q v s v ~t v u v g v ~h v ~c v m v ~pp , 
p v q v s v ~t v u v g v ~h v ~c v ~m v pp , p v q v s v ~t v u v g v ~h v ~c v ~m v ~pp , 
p v q v s v ~t v u v ~g v h v c v m v pp , p v q v s v ~t v u v ~g v h v c v m v ~pp , 
p v q v s v ~t v u v ~g v h v c v ~m v pp , p v q v s v ~t v u v ~g v h v c v ~m v ~pp , 
p v q v s v ~t v u v ~g v h v ~c v m v pp , p v q v s v ~t v u v ~g v h v ~c v m v ~pp , 
p v q v s v ~t v u v ~g v h v ~c v ~m v pp , p v q v s v ~t v u v ~g v h v ~c v ~m v ~pp , 
p v q v s v ~t v u v ~g v ~h v c v m v pp , p v q v s v ~t v u v ~g v ~h v c v m v ~pp , 
p v q v s v ~t v u v ~g v ~h v c v ~m v pp , p v q v s v ~t v u v ~g v ~h v c v ~m v ~pp , 
p v q v s v ~t v u v ~g v ~h v ~c v m v pp , p v q v s v ~t v u v ~g v ~h v ~c v m v ~pp , 
p v q v s v ~t v u v ~g v ~h v ~c v ~m v pp , p v q v s v ~t v u v ~g v ~h v ~c v ~m v ~pp , 
p v q v s v ~t v ~u v g v h v c v m v pp , p v q v s v ~t v ~u v g v h v c v m v ~pp , 
p v q v s v ~t v ~u v g v h v c v ~m v pp , p v q v s v ~t v ~u v g v h v c v ~m v ~pp , 
p v q v s v ~t v ~u v g v h v ~c v m v pp , p v q v s v ~t v ~u v g v h v ~c v m v ~pp , 
p v q v s v ~t v ~u v g v h v ~c v ~m v pp , p v q v s v ~t v ~u v g v h v ~c v ~m v ~pp , 
p v q v s v ~t v ~u v g v ~h v c v m v pp , p v q v s v ~t v ~u v g v ~h v c v m v ~pp , 
p v q v s v ~t v ~u v g v ~h v c v ~m v pp , p v q v s v ~t v ~u v g v ~h v c v ~m v ~pp , 
p v q v s v ~t v ~u v g v ~h v ~c v m v pp , p v q v s v ~t v ~u v g v ~h v ~c v m v ~pp , 
p v q v s v ~t v ~u v g v ~h v ~c v ~m v pp , p v q v s v ~t v ~u v g v ~h v ~c v ~m v ~pp , 
p v q v s v ~t v ~u v ~g v h v c v m v pp , p v q v s v ~t v ~u v ~g v h v c v m v ~pp , 
p v q v s v ~t v ~u v ~g v h v c v ~m v pp , p v q v s v ~t v ~u v ~g v h v c v ~m v ~pp , 
p v q v s v ~t v ~u v ~g v h v ~c v m v pp , p v q v s v ~t v ~u v ~g v h v ~c v m v ~pp , 
p v q v s v ~t v ~u v ~g v h v ~c v ~m v pp , p v q v s v ~t v ~u v ~g v h v ~c v ~m v ~pp , 
p v q v s v ~t v ~u v ~g v ~h v c v m v pp , p v q v s v ~t v ~u v ~g v ~h v c v m v ~pp , 
p v q v s v ~t v ~u v ~g v ~h v c v ~m v pp , p v q v s v ~t v ~u v ~g v ~h v c v ~m v ~pp , 
p v q v s v ~t v ~u v ~g v ~h v ~c v m v pp , p v q v s v ~t v ~u v ~g v ~h v ~c v m v ~pp , 
p v q v s v ~t v ~u v ~g v ~h v ~c v ~m v pp , p v q v s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp , 
p v q v ~s v t v u v g v h v c v m v pp , p v q v ~s v t v u v g v h v c v m v ~pp , 
p v q v ~s v t v u v g v h v c v ~m v pp , p v q v ~s v t v u v g v h v c v ~m v ~pp , 
p v q v ~s v t v u v g v h v ~c v m v pp , p v q v ~s v t v u v g v h v ~c v m v ~pp , 
p v q v ~s v t v u v g v h v ~c v ~m v pp , p v q v ~s v t v u v g v h v ~c v ~m v ~pp , 
p v q v ~s v t v u v g v ~h v c v m v pp , p v q v ~s v t v u v g v ~h v c v m v ~pp , 
p v q v ~s v t v u v g v ~h v c v ~m v pp , p v q v ~s v t v u v g v ~h v c v ~m v ~pp , 
p v q v ~s v t v u v g v ~h v ~c v m v pp , p v q v ~s v t v u v g v ~h v ~c v m v ~pp , 
p v q v ~s v t v u v g v ~h v ~c v ~m v pp , p v q v ~s v t v u v g v ~h v ~c v ~m v ~pp , 
p v q v ~s v t v u v ~g v h v c v m v pp , p v q v ~s v t v u v ~g v h v c v m v ~pp , 
p v q v ~s v t v u v ~g v h v c v ~m v pp , p v q v ~s v t v u v ~g v h v c v ~m v ~pp , 
p v q v ~s v t v u v ~g v h v ~c v m v pp , p v q v ~s v t v u v ~g v h v ~c v m v ~pp , 
p v q v ~s v t v u v ~g v h v ~c v ~m v pp , p v q v ~s v t v u v ~g v h v ~c v ~m v ~pp , 
p v q v ~s v t v u v ~g v ~h v c v m v pp , p v q v ~s v t v u v ~g v ~h v c v m v ~pp , 
p v q v ~s v t v u v ~g v ~h v c v ~m v pp , p v q v ~s v t v u v ~g v ~h v c v ~m v ~pp , 
p v q v ~s v t v u v ~g v ~h v ~c v m v pp , p v q v ~s v t v u v ~g v ~h v ~c v m v ~pp , 
p v q v ~s v t v u v ~g v ~h v ~c v ~m v pp , p v q v ~s v t v u v ~g v ~h v ~c v ~m v ~pp , 
p v q v ~s v t v ~u v g v h v c v m v pp , p v q v ~s v t v ~u v g v h v c v m v ~pp , 
p v q v ~s v t v ~u v g v h v c v ~m v pp , p v q v ~s v t v ~u v g v h v c v ~m v ~pp , 
p v q v ~s v t v ~u v g v h v ~c v m v pp , p v q v ~s v t v ~u v g v h v ~c v m v ~pp , 
p v q v ~s v t v ~u v g v h v ~c v ~m v pp , p v q v ~s v t v ~u v g v h v ~c v ~m v ~pp , 
p v q v ~s v t v ~u v g v ~h v c v m v pp , p v q v ~s v t v ~u v g v ~h v c v m v ~pp , 
p v q v ~s v t v ~u v g v ~h v c v ~m v pp , p v q v ~s v t v ~u v g v ~h v c v ~m v ~pp , 
p v q v ~s v t v ~u v g v ~h v ~c v m v pp , p v q v ~s v t v ~u v g v ~h v ~c v m v ~pp , 
p v q v ~s v t v ~u v g v ~h v ~c v ~m v pp , p v q v ~s v t v ~u v g v ~h v ~c v ~m v ~pp , 
p v q v ~s v t v ~u v ~g v h v c v m v pp , p v q v ~s v t v ~u v ~g v h v c v m v ~pp , 
p v q v ~s v t v ~u v ~g v h v c v ~m v pp , p v q v ~s v t v ~u v ~g v h v c v ~m v ~pp , 
p v q v ~s v t v ~u v ~g v h v ~c v m v pp , p v q v ~s v t v ~u v ~g v h v ~c v m v ~pp , 
p v q v ~s v t v ~u v ~g v h v ~c v ~m v pp , p v q v ~s v t v ~u v ~g v h v ~c v ~m v ~pp , 
p v q v ~s v t v ~u v ~g v ~h v c v m v pp , p v q v ~s v t v ~u v ~g v ~h v c v m v ~pp , 
p v q v ~s v t v ~u v ~g v ~h v c v ~m v pp , p v q v ~s v t v ~u v ~g v ~h v c v ~m v ~pp , 
p v q v ~s v t v ~u v ~g v ~h v ~c v m v pp , p v q v ~s v t v ~u v ~g v ~h v ~c v m v ~pp , 
p v q v ~s v t v ~u v ~g v ~h v ~c v ~m v pp , p v q v ~s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
p v q v ~s v ~t v u v g v h v c v m v pp , p v q v ~s v ~t v u v g v h v c v m v ~pp , 
p v q v ~s v ~t v u v g v h v c v ~m v pp , p v q v ~s v ~t v u v g v h v c v ~m v ~pp , 
p v q v ~s v ~t v u v g v h v ~c v m v pp , p v q v ~s v ~t v u v g v h v ~c v m v ~pp , 
p v q v ~s v ~t v ~u v ~g v h v c v m v ~pp , p v q v ~s v ~t v ~u v ~g v h v c v ~m v pp , 
p v q v ~s v ~t v ~u v ~g v h v c v ~m v ~pp , p v q v ~s v ~t v ~u v ~g v h v ~c v m v pp , 
p v q v ~s v ~t v ~u v ~g v h v ~c v m v ~pp , p v q v ~s v ~t v ~u v ~g v h v ~c v ~m v pp , 
p v q v ~s v ~t v ~u v ~g v h v ~c v ~m v ~pp , p v q v ~s v ~t v ~u v ~g v ~h v c v m v pp , 
p v q v ~s v ~t v ~u v ~g v ~h v c v m v ~pp , p v q v ~s v ~t v ~u v ~g v ~h v c v ~m v pp , 
p v q v ~s v ~t v ~u v ~g v ~h v c v ~m v ~pp , p v q v ~s v ~t v ~u v ~g v ~h v ~c v m v pp , 
p v q v ~s v ~t v ~u v ~g v ~h v ~c v m v ~pp , p v q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v pp , 
p v q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp , p v ~q v s v t v u v g v h v c v m v pp , 
p v ~q v s v t v u v g v h v c v m v ~pp , p v ~q v s v t v u v g v h v c v ~m v pp , 
p v ~q v s v t v u v g v h v c v ~m v ~pp , p v ~q v s v t v u v g v h v ~c v m v pp , 
p v ~q v s v t v u v g v h v ~c v m v ~pp , p v ~q v s v t v u v g v h v ~c v ~m v pp , 
p v ~q v s v t v u v g v h v ~c v ~m v ~pp , p v ~q v s v t v u v g v ~h v c v m v pp , 
p v ~q v s v t v u v g v ~h v c v m v ~pp , p v ~q v s v t v u v g v ~h v c v ~m v pp , 
p v ~q v s v t v u v g v ~h v c v ~m v ~pp , p v ~q v s v t v u v g v ~h v ~c v m v pp , 
p v ~q v s v t v u v g v ~h v ~c v m v ~pp , p v ~q v s v t v u v g v ~h v ~c v ~m v pp , 
p v ~q v s v t v u v g v ~h v ~c v ~m v ~pp , p v ~q v s v t v u v ~g v h v c v m v pp , 
p v ~q v s v t v ~u v ~g v ~h v c v m v pp , p v ~q v s v t v ~u v ~g v ~h v c v m v ~pp , 
p v ~q v s v t v ~u v ~g v ~h v c v ~m v pp , p v ~q v s v t v ~u v ~g v ~h v c v ~m v ~pp , 
p v ~q v s v t v ~u v ~g v ~h v ~c v m v pp , p v ~q v s v t v ~u v ~g v ~h v ~c v m v ~pp , 
p v ~q v s v t v ~u v ~g v ~h v ~c v ~m v pp , p v ~q v s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
p v ~q v s v ~t v u v g v h v c v m v pp , p v ~q v s v ~t v u v g v h v c v m v ~pp , 
p v ~q v s v ~t v u v g v h v c v ~m v pp , p v ~q v s v ~t v u v g v h v c v ~m v ~pp , 
p v ~q v s v ~t v u v g v h v ~c v m v ~pp , p v ~q v s v ~t v u v g v h v ~c v ~m v pp , 
p v ~q v s v ~t v u v g v h v ~c v ~m v ~pp , p v ~q v s v ~t v u v g v ~h v c v m v pp , 
p v ~q v s v ~t v u v g v ~h v c v m v ~pp , p v ~q v s v ~t v u v g v ~h v c v ~m v pp , 
p v ~q v s v ~t v ~u v g v h v c v ~m v pp , p v ~q v s v ~t v ~u v g v h v c v ~m v ~pp , 
p v ~q v s v ~t v ~u v g v h v ~c v m v pp , p v ~q v s v ~t v ~u v g v h v ~c v m v ~pp , 
p v ~q v s v ~t v ~u v g v h v ~c v ~m v pp , p v ~q v s v ~t v ~u v g v h v ~c v ~m v ~pp , 
p v ~q v s v ~t v ~u v g v ~h v c v m v pp , p v ~q v s v ~t v ~u v g v ~h v c v m v ~pp , 
p v ~q v s v ~t v ~u v g v ~h v c v ~m v pp , p v ~q v s v ~t v ~u v g v ~h v c v ~m v ~pp , 
p v ~q v s v ~t v ~u v g v ~h v ~c v m v ~pp , p v ~q v s v ~t v ~u v g v ~h v ~c v ~m v pp , 
p v ~q v s v ~t v ~u v g v ~h v ~c v ~m v ~pp , p v ~q v s v ~t v ~u v ~g v h v c v m v pp , 
p v ~q v s v ~t v ~u v ~g v h v c v m v ~pp , p v ~q v s v ~t v ~u v ~g v h v c v ~m v pp , 
p v ~q v s v ~t v ~u v ~g v h v c v ~m v ~pp , p v ~q v s v ~t v ~u v ~g v h v ~c v m v pp , 
p v ~q v s v ~t v ~u v ~g v h v ~c v m v ~pp , p v ~q v s v ~t v ~u v ~g v h v ~c v ~m v pp , 
p v ~q v s v ~t v ~u v ~g v h v ~c v ~m v ~pp , p v ~q v s v ~t v ~u v ~g v ~h v c v m v pp , 
p v ~q v ~s v t v u v ~g v h v c v m v pp , p v ~q v ~s v t v u v ~g v h v c v m v ~pp , 
p v ~q v ~s v t v ~u v g v ~h v c v m v pp , p v ~q v ~s v t v ~u v g v ~h v c v m v ~pp , 
p v ~q v ~s v t v ~u v g v ~h v c v ~m v pp , p v ~q v ~s v t v ~u v g v ~h v c v ~m v ~pp , 
p v ~q v ~s v t v ~u v g v ~h v ~c v m v pp , p v ~q v ~s v t v ~u v g v ~h v ~c v m v ~pp , 
p v ~q v ~s v t v ~u v g v ~h v ~c v ~m v pp , p v ~q v ~s v t v ~u v g v ~h v ~c v ~m v ~pp , 
p v ~q v ~s v t v ~u v ~g v h v c v m v pp , p v ~q v ~s v t v ~u v ~g v h v c v m v ~pp , 
p v ~q v ~s v t v ~u v ~g v h v c v ~m v pp , p v ~q v ~s v t v ~u v ~g v h v c v ~m v ~pp , 
p v ~q v ~s v t v ~u v ~g v ~h v ~c v m v pp , p v ~q v ~s v t v ~u v ~g v ~h v ~c v m v ~pp , 
p v ~q v ~s v t v ~u v ~g v ~h v ~c v ~m v pp , p v ~q v ~s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
p v ~q v ~s v ~t v u v g v h v c v m v pp , p v ~q v ~s v ~t v u v g v h v c v m v ~pp , 
p v ~q v ~s v ~t v u v g v h v c v ~m v pp , p v ~q v ~s v ~t v u v g v h v c v ~m v ~pp , 
p v ~q v ~s v ~t v u v g v h v ~c v m v pp , p v ~q v ~s v ~t v u v g v h v ~c v m v ~pp , 
p v ~q v ~s v ~t v u v g v h v ~c v ~m v pp , p v ~q v ~s v ~t v u v g v h v ~c v ~m v ~pp , 
p v ~q v ~s v ~t v u v g v ~h v c v m v pp , p v ~q v ~s v ~t v u v g v ~h v c v m v ~pp , 
p v ~q v ~s v ~t v u v g v ~h v c v ~m v pp , p v ~q v ~s v ~t v u v g v ~h v c v ~m v ~pp , 
p v ~q v ~s v ~t v u v g v ~h v ~c v m v pp , p v ~q v ~s v ~t v u v g v ~h v ~c v m v ~pp , 
p v ~q v ~s v ~t v u v g v ~h v ~c v ~m v pp , p v ~q v ~s v ~t v u v ~g v ~h v c v m v pp , 
p v ~q v ~s v ~t v u v ~g v ~h v c v m v ~pp , p v ~q v ~s v ~t v u v ~g v ~h v c v ~m v pp , 
p v ~q v ~s v ~t v u v ~g v ~h v c v ~m v ~pp , p v ~q v ~s v ~t v u v ~g v ~h v ~c v m v pp , 
p v ~q v ~s v ~t v u v ~g v ~h v ~c v m v ~pp , p v ~q v ~s v ~t v ~u v ~g v h v ~c v ~m v ~pp , 
p v ~q v ~s v ~t v ~u v ~g v ~h v c v m v pp , p v ~q v ~s v ~t v ~u v ~g v ~h v c v m v ~pp , 
p v ~q v ~s v ~t v ~u v ~g v ~h v c v ~m v pp , p v ~q v ~s v ~t v ~u v ~g v ~h v c v ~m v ~pp , 
p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v m v pp , p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v m v ~pp , 
p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v pp , p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v q v s v t v u v g v h v c v m v pp , ~p v q v s v t v u v g v h v c v m v ~pp , 
~p v q v s v t v u v g v h v c v ~m v pp , ~p v q v s v t v u v g v h v c v ~m v ~pp ,
 ~p v q v s v t v u v g v h v ~c v m v pp ,~p v q v s v t v u v g v h v ~c v m v ~pp , 
~p v q v s v t v u v g v h v ~c v ~m v ~pp , ~p v q v s v t v u v g v ~h v c v m v pp , 
~p v q v s v t v u v ~g v h v ~c v ~m v ~pp , ~p v q v s v t v u v ~g v ~h v c v m v pp , 
~p v q v s v t v u v ~g v ~h v c v m v ~pp , ~p v q v s v t v u v ~g v ~h v c v ~m v pp , 
~p v q v s v t v u v ~g v ~h v c v ~m v ~pp , ~p v q v s v t v ~u v ~g v h v c v m v pp , 
~p v q v s v t v ~u v ~g v h v c v m v ~pp , ~p v q v s v t v ~u v ~g v h v c v ~m v pp , 
~p v q v s v t v ~u v ~g v h v c v ~m v ~pp , ~p v q v s v t v ~u v ~g v h v ~c v m v pp , 
~p v q v s v t v ~u v ~g v h v ~c v m v ~pp , ~p v q v s v t v ~u v ~g v h v ~c v ~m v pp , 
~p v q v s v t v ~u v ~g v h v ~c v ~m v ~pp , ~p v q v s v t v ~u v ~g v ~h v c v m v pp , 
~p v q v s v t v ~u v ~g v ~h v c v m v ~pp , ~p v q v s v t v ~u v ~g v ~h v c v ~m v pp , 
~p v q v s v t v ~u v ~g v ~h v c v ~m v ~pp , ~p v q v s v t v ~u v ~g v ~h v ~c v m v pp , 
~p v q v s v t v ~u v ~g v ~h v ~c v m v ~pp , ~p v q v s v t v ~u v ~g v ~h v ~c v ~m v pp , 
~p v q v s v t v ~u v ~g v ~h v ~c v ~m v ~pp , ~p v q v s v ~t v u v g v h v c v m v pp , 
~p v q v s v ~t v u v g v h v ~c v ~m v ~pp , ~p v q v s v ~t v u v g v ~h v c v m v pp , 
~p v q v s v ~t v u v g v ~h v c v m v ~pp , ~p v q v s v ~t v u v g v ~h v c v ~m v pp , 
~p v q v s v ~t v u v g v ~h v c v ~m v ~pp , ~p v q v s v ~t v u v g v ~h v ~c v m v pp , 
~p v q v s v ~t v u v g v ~h v ~c v m v ~pp , ~p v q v s v ~t v u v g v ~h v ~c v ~m v pp , 
~p v q v s v ~t v u v g v ~h v ~c v ~m v ~pp , ~p v q v s v ~t v u v ~g v h v c v m v pp , 
~p v q v s v ~t v ~u v ~g v ~h v c v m v pp , ~p v q v s v ~t v ~u v ~g v ~h v c v m v ~pp , 
~p v q v s v ~t v ~u v ~g v ~h v c v ~m v pp , ~p v q v s v ~t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v q v s v ~t v ~u v ~g v ~h v ~c v m v pp , ~p v q v s v ~t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v q v s v ~t v ~u v ~g v ~h v ~c v ~m v pp , ~p v q v s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v t v u v g v h v c v m v pp , ~p v q v ~s v t v u v g v h v c v m v ~pp , 
~p v q v ~s v t v u v g v h v c v ~m v pp , ~p v q v ~s v t v u v g v h v c v ~m v ~pp , 
~p v q v ~s v t v u v g v h v ~c v m v pp , ~p v q v ~s v t v u v g v h v ~c v m v ~pp , 
~p v q v ~s v t v u v g v h v ~c v ~m v pp , ~p v q v ~s v t v u v g v h v ~c v ~m v ~pp , 
~p v q v ~s v t v u v g v ~h v c v m v pp , ~p v q v ~s v t v u v g v ~h v c v m v ~pp , 
~p v q v ~s v t v u v g v ~h v c v ~m v pp , ~p v q v ~s v t v u v g v ~h v c v ~m v ~pp , 
~p v q v ~s v t v u v g v ~h v ~c v m v pp , ~p v q v ~s v t v u v g v ~h v ~c v m v ~pp , 
~p v q v ~s v t v u v g v ~h v ~c v ~m v pp , ~p v q v ~s v t v u v g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v t v u v ~g v h v c v m v pp , ~p v q v ~s v t v u v ~g v h v c v m v ~pp , 
~p v q v ~s v t v u v ~g v h v c v ~m v pp , ~p v q v ~s v t v u v ~g v h v c v ~m v ~pp , 
~p v q v ~s v t v u v ~g v h v ~c v m v pp , ~p v q v ~s v t v u v ~g v h v ~c v m v ~pp , 
~p v q v ~s v t v u v ~g v h v ~c v ~m v pp , ~p v q v ~s v t v u v ~g v h v ~c v ~m v ~pp , 
~p v q v ~s v t v u v ~g v ~h v c v m v pp , ~p v q v ~s v t v u v ~g v ~h v c v m v ~pp , 
~p v q v ~s v t v u v ~g v ~h v c v ~m v pp , ~p v q v ~s v t v u v ~g v ~h v c v ~m v ~pp , 
~p v q v ~s v t v u v ~g v ~h v ~c v m v pp , ~p v q v ~s v t v u v ~g v ~h v ~c v m v ~pp , 
~p v q v ~s v t v u v ~g v ~h v ~c v ~m v pp , ~p v q v ~s v t v u v ~g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v t v ~u v g v h v c v m v pp , ~p v q v ~s v t v ~u v g v h v c v m v ~pp , 
~p v q v ~s v t v ~u v g v h v c v ~m v pp ,~p v q v ~s v t v ~u v g v h v c v ~m v ~pp , 
~p v q v ~s v t v ~u v g v h v ~c v m v pp , ~p v q v ~s v t v ~u v g v h v ~c v m v ~pp , 
~p v q v ~s v t v ~u v g v h v ~c v ~m v pp , ~p v q v ~s v t v ~u v g v h v ~c v ~m v ~pp , 
~p v q v ~s v t v ~u v g v ~h v c v m v pp , ~p v q v ~s v t v ~u v g v ~h v c v m v ~pp , 
~p v q v ~s v t v ~u v g v ~h v c v ~m v pp , ~p v q v ~s v t v ~u v g v ~h v c v ~m v ~pp , 
~p v q v ~s v t v ~u v g v ~h v ~c v m v pp , ~p v q v ~s v t v ~u v g v ~h v ~c v m v ~pp , 
~p v q v ~s v t v ~u v g v ~h v ~c v ~m v pp , ~p v q v ~s v t v ~u v g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v t v ~u v ~g v h v c v m v pp , ~p v q v ~s v t v ~u v ~g v h v c v m v ~pp , 
~p v q v ~s v t v ~u v ~g v h v c v ~m v pp , ~p v q v ~s v t v ~u v ~g v h v c v ~m v ~pp , 
~p v q v ~s v t v ~u v ~g v h v ~c v m v pp , ~p v q v ~s v t v ~u v ~g v h v ~c v m v ~pp , 
~p v q v ~s v t v ~u v ~g v h v ~c v ~m v pp , ~p v q v ~s v t v ~u v ~g v h v ~c v ~m v ~pp , 
~p v q v ~s v t v ~u v ~g v ~h v c v m v pp , ~p v q v ~s v t v ~u v ~g v ~h v c v m v ~pp , 
~p v q v ~s v t v ~u v ~g v ~h v c v ~m v pp , ~p v q v ~s v t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v q v ~s v t v ~u v ~g v ~h v ~c v m v pp , ~p v q v ~s v t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v q v ~s v t v ~u v ~g v ~h v ~c v ~m v pp , ~p v q v ~s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v u v g v h v c v m v pp , ~p v q v ~s v ~t v u v g v h v c v m v ~pp , 
~p v q v ~s v ~t v u v g v h v c v ~m v pp , ~p v q v ~s v ~t v u v g v h v c v ~m v ~pp , 
~p v q v ~s v ~t v u v g v h v ~c v m v pp , ~p v q v ~s v ~t v u v g v h v ~c v m v ~pp , 
~p v q v ~s v ~t v u v g v h v ~c v ~m v pp , ~p v q v ~s v ~t v u v g v h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v u v g v ~h v c v m v pp , ~p v q v ~s v ~t v u v g v ~h v c v m v ~pp , 
~p v q v ~s v ~t v u v g v ~h v c v ~m v pp , ~p v q v ~s v ~t v u v g v ~h v c v ~m v ~pp , 
~p v q v ~s v ~t v u v g v ~h v ~c v m v pp , ~p v q v ~s v ~t v u v g v ~h v ~c v m v ~pp , 
~p v q v ~s v ~t v u v g v ~h v ~c v ~m v pp , ~p v q v ~s v ~t v u v g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v u v ~g v h v c v m v pp , ~p v q v ~s v ~t v u v ~g v h v c v m v ~pp , 
~p v q v ~s v ~t v u v ~g v h v c v ~m v pp , ~p v q v ~s v ~t v u v ~g v h v c v ~m v ~pp , 
~p v q v ~s v ~t v u v ~g v h v ~c v m v pp , ~p v q v ~s v ~t v u v ~g v h v ~c v m v ~pp , 
~p v q v ~s v ~t v u v ~g v h v ~c v ~m v pp , ~p v q v ~s v ~t v u v ~g v h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v u v ~g v ~h v c v m v pp , ~p v q v ~s v ~t v u v ~g v ~h v c v m v ~pp , 
~p v q v ~s v ~t v u v ~g v ~h v c v ~m v pp , ~p v q v ~s v ~t v u v ~g v ~h v c v ~m v ~pp , 
~p v q v ~s v ~t v u v ~g v ~h v ~c v m v pp , ~p v q v ~s v ~t v u v ~g v ~h v ~c v m v ~pp , 
~p v q v ~s v ~t v u v ~g v ~h v ~c v ~m v pp , ~p v q v ~s v ~t v u v ~g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v g v h v c v m v pp , ~p v q v ~s v ~t v ~u v g v h v c v m v ~pp , 
~p v q v ~s v ~t v ~u v g v h v c v ~m v pp , ~p v q v ~s v ~t v ~u v g v h v c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v g v h v ~c v m v pp , ~p v q v ~s v ~t v ~u v g v h v ~c v m v ~pp , 
~p v q v ~s v ~t v ~u v g v h v ~c v ~m v pp , ~p v q v ~s v ~t v ~u v g v h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v g v ~h v c v m v pp , ~p v q v ~s v ~t v ~u v g v ~h v c v m v ~pp , 
~p v q v ~s v ~t v ~u v g v ~h v c v ~m v pp , ~p v q v ~s v ~t v ~u v g v ~h v c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v g v ~h v ~c v m v pp , ~p v q v ~s v ~t v ~u v g v ~h v ~c v m v ~pp , 
~p v q v ~s v ~t v ~u v g v ~h v ~c v ~m v pp , ~p v q v ~s v ~t v ~u v g v ~h v ~c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v ~g v h v c v m v pp , ~p v q v ~s v ~t v ~u v ~g v h v c v m v ~pp , 
~p v q v ~s v ~t v ~u v ~g v h v c v ~m v pp , ~p v q v ~s v ~t v ~u v ~g v h v c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v ~g v h v ~c v m v pp , ~p v q v ~s v ~t v ~u v ~g v h v ~c v m v ~pp ,
 ~p v q v ~s v ~t v ~u v ~g v h v ~c v ~m v pp , ~p v q v ~s v ~t v ~u v ~g v h v ~c v ~m v ~pp, 
~p v q v ~s v ~t v ~u v ~g v ~h v c v m v pp , ~p v q v ~s v ~t v ~u v ~g v ~h v c v m v ~pp , 
~p v q v ~s v ~t v ~u v ~g v ~h v c v ~m v pp , ~p v q v ~s v ~t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v q v ~s v ~t v ~u v ~g v ~h v ~c v m v pp , ~p v q v ~s v ~t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v pp , ~p v q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v t v u v g v h v c v m v pp , ~p v ~q v s v t v u v g v h v c v m v ~pp , 
~p v ~q v s v t v u v g v h v c v ~m v pp , ~p v ~q v s v t v u v g v h v c v ~m v ~pp , 
~p v ~q v s v t v u v g v h v ~c v m v pp , ~p v ~q v s v t v u v g v h v ~c v m v ~pp , 
~p v ~q v s v t v u v g v h v ~c v ~m v pp , ~p v ~q v s v t v u v g v h v ~c v ~m v ~pp , 
~p v ~q v s v t v u v g v ~h v c v m v pp , ~p v ~q v s v t v u v g v ~h v c v m v ~pp , 
~p v ~q v s v t v u v g v ~h v c v ~m v pp , ~p v ~q v s v t v u v g v ~h v c v ~m v ~pp , 
~p v ~q v s v t v u v g v ~h v ~c v m v pp , ~p v ~q v s v t v u v g v ~h v ~c v m v ~pp , 
~p v ~q v s v t v u v g v ~h v ~c v ~m v pp , ~p v ~q v s v t v u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v t v u v ~g v h v c v m v pp , ~p v ~q v s v t v u v ~g v h v c v m v ~pp , 
~p v ~q v s v t v u v ~g v h v c v ~m v pp , ~p v ~q v s v t v u v ~g v h v c v ~m v ~pp , 
~p v ~q v s v t v u v ~g v h v ~c v m v pp , ~p v ~q v s v t v u v ~g v h v ~c v m v ~pp , 
~p v ~q v s v t v u v ~g v h v ~c v ~m v pp , ~p v ~q v s v t v u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v s v t v u v ~g v ~h v c v m v pp , ~p v ~q v s v t v u v ~g v ~h v c v m v ~pp , 
~p v ~q v s v t v u v ~g v ~h v c v ~m v pp , ~p v ~q v s v t v u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v s v t v u v ~g v ~h v ~c v m v pp , ~p v ~q v s v t v u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v s v t v u v ~g v ~h v ~c v ~m v pp , ~p v ~q v s v t v u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v t v ~u v g v h v c v m v pp , ~p v ~q v s v t v ~u v g v h v c v m v ~pp , 
~p v ~q v s v t v ~u v g v h v c v ~m v pp , ~p v ~q v s v t v ~u v g v h v c v ~m v ~pp , 
~p v ~q v s v t v ~u v g v h v ~c v m v pp , ~p v ~q v s v t v ~u v g v h v ~c v m v ~pp , 
~p v ~q v s v t v ~u v g v h v ~c v ~m v pp , ~p v ~q v s v t v ~u v g v h v ~c v ~m v ~pp , 
~p v ~q v s v t v ~u v g v ~h v c v m v pp , ~p v ~q v s v t v ~u v g v ~h v c v m v ~pp , 
~p v ~q v s v t v ~u v g v ~h v c v ~m v pp , ~p v ~q v s v t v ~u v g v ~h v c v ~m v ~pp , 
~p v ~q v s v t v ~u v g v ~h v ~c v m v pp , ~p v ~q v s v t v ~u v g v ~h v ~c v m v ~pp , 
~p v ~q v s v t v ~u v g v ~h v ~c v ~m v pp , ~p v ~q v s v t v ~u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v t v ~u v ~g v h v c v m v pp , ~p v ~q v s v t v ~u v ~g v h v c v m v ~pp , 
~p v ~q v s v t v ~u v ~g v h v c v ~m v pp , ~p v ~q v s v t v ~u v ~g v h v c v ~m v ~pp , 
~p v ~q v s v t v ~u v ~g v h v ~c v m v pp , ~p v ~q v s v t v ~u v ~g v h v ~c v m v ~pp , 
~p v ~q v s v t v ~u v ~g v h v ~c v ~m v pp , ~p v ~q v s v t v ~u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v s v t v ~u v ~g v ~h v c v m v pp , ~p v ~q v s v t v ~u v ~g v ~h v c v m v ~pp , 
~p v ~q v s v t v ~u v ~g v ~h v c v ~m v pp , ~p v ~q v s v t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v s v t v ~u v ~g v ~h v ~c v m v pp , ~p v ~q v s v t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v s v t v ~u v ~g v ~h v ~c v ~m v pp , ~p v ~q v s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v u v g v h v c v m v pp , ~p v ~q v s v ~t v u v g v h v c v m v ~pp , 
~p v ~q v s v ~t v u v g v h v c v ~m v pp , ~p v ~q v s v ~t v u v g v h v c v ~m v ~pp , 
~p v ~q v s v ~t v u v g v h v ~c v m v pp , ~p v ~q v s v ~t v u v g v h v ~c v m v ~pp , 
~p v ~q v s v ~t v u v g v h v ~c v ~m v pp , ~p v ~q v s v ~t v u v g v h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v u v g v ~h v c v m v pp , ~p v ~q v s v ~t v u v g v ~h v c v m v ~pp , 
~p v ~q v s v ~t v u v g v ~h v c v ~m v pp , ~p v ~q v s v ~t v u v g v ~h v c v ~m v ~pp , 
~p v ~q v s v ~t v u v g v ~h v ~c v m v pp , ~p v ~q v s v ~t v u v g v ~h v ~c v m v ~pp , 
~p v ~q v s v ~t v u v g v ~h v ~c v ~m v pp , ~p v ~q v s v ~t v u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v u v ~g v h v c v m v pp , ~p v ~q v s v ~t v u v ~g v h v c v m v ~pp , 
~p v ~q v s v ~t v u v ~g v h v c v ~m v pp , ~p v ~q v s v ~t v u v ~g v h v c v ~m v ~pp , 
~p v ~q v s v ~t v u v ~g v h v ~c v m v pp , ~p v ~q v s v ~t v u v ~g v h v ~c v m v ~pp , 
~p v ~q v s v ~t v u v ~g v h v ~c v ~m v pp , ~p v ~q v s v ~t v u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v u v ~g v ~h v c v m v pp , ~p v ~q v s v ~t v u v ~g v ~h v c v m v ~pp , 
~p v ~q v s v ~t v u v ~g v ~h v c v ~m v pp , ~p v ~q v s v ~t v u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v s v ~t v u v ~g v ~h v ~c v m v pp , ~p v ~q v s v ~t v u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v s v ~t v u v ~g v ~h v ~c v ~m v pp , ~p v ~q v s v ~t v u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v g v h v c v m v pp , ~p v ~q v s v ~t v ~u v g v h v c v m v ~pp , 
~p v ~q v s v ~t v ~u v g v h v c v ~m v pp , ~p v ~q v s v ~t v ~u v g v h v c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v g v h v ~c v m v pp , ~p v ~q v s v ~t v ~u v g v h v ~c v m v ~pp , 
~p v ~q v s v ~t v ~u v g v h v ~c v ~m v pp , ~p v ~q v s v ~t v ~u v g v h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v g v ~h v c v m v pp , ~p v ~q v s v ~t v ~u v g v ~h v c v m v ~pp , 
~p v ~q v s v ~t v ~u v g v ~h v c v ~m v pp , ~p v ~q v s v ~t v ~u v g v ~h v c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v g v ~h v ~c v m v pp , ~p v ~q v s v ~t v ~u v g v ~h v ~c v m v ~pp , 
~p v ~q v s v ~t v ~u v g v ~h v ~c v ~m v pp , ~p v ~q v s v ~t v ~u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v h v c v m v pp , ~p v ~q v s v ~t v ~u v ~g v h v c v m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v h v c v ~m v pp , ~p v ~q v s v ~t v ~u v ~g v h v c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v h v ~c v m v pp , ~p v ~q v s v ~t v ~u v ~g v h v ~c v m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v h v ~c v ~m v pp , ~p v ~q v s v ~t v ~u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v ~h v c v m v pp , ~p v ~q v s v ~t v ~u v ~g v ~h v c v m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v ~h v c v ~m v pp , ~p v ~q v s v ~t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v ~h v ~c v m v pp , ~p v ~q v s v ~t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v s v ~t v ~u v ~g v ~h v ~c v ~m v pp , ~p v ~q v s v ~t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v u v g v h v c v m v pp , ~p v ~q v ~s v t v u v g v h v c v m v ~pp , 
~p v ~q v ~s v t v u v g v h v c v ~m v pp , ~p v ~q v ~s v t v u v g v h v c v ~m v ~pp , 
~p v ~q v ~s v t v u v g v h v ~c v m v pp , ~p v ~q v ~s v t v u v g v h v ~c v m v ~pp , 
~p v ~q v ~s v t v u v g v h v ~c v ~m v pp , ~p v ~q v ~s v t v u v g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v u v g v ~h v c v m v pp , ~p v ~q v ~s v t v u v g v ~h v c v m v ~pp , 
~p v ~q v ~s v t v u v g v ~h v c v ~m v pp , ~p v ~q v ~s v t v u v g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v t v u v g v ~h v ~c v m v pp , ~p v ~q v ~s v t v u v g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v t v u v g v ~h v ~c v ~m v pp , ~p v ~q v ~s v t v u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v u v ~g v h v c v m v pp , ~p v ~q v ~s v t v u v ~g v h v c v m v ~pp , 
~p v ~q v ~s v t v u v ~g v h v c v ~m v pp , ~p v ~q v ~s v t v u v ~g v h v c v ~m v ~pp , 
~p v ~q v ~s v t v u v ~g v h v ~c v m v pp , ~p v ~q v ~s v t v u v ~g v h v ~c v m v ~pp , 
~p v ~q v ~s v t v u v ~g v h v ~c v ~m v pp , ~p v ~q v ~s v t v u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v u v ~g v ~h v c v m v pp , ~p v ~q v ~s v t v u v ~g v ~h v c v m v ~pp , 
~p v ~q v ~s v t v u v ~g v ~h v c v ~m v pp , ~p v ~q v ~s v t v u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v t v u v ~g v ~h v ~c v m v pp , ~p v ~q v ~s v t v u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v t v u v ~g v ~h v ~c v ~m v pp , ~p v ~q v ~s v t v u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v g v h v c v m v pp , ~p v ~q v ~s v t v ~u v g v h v c v m v ~pp , 
~p v ~q v ~s v t v ~u v g v h v c v ~m v pp , ~p v ~q v ~s v t v ~u v g v h v c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v g v h v ~c v m v pp , ~p v ~q v ~s v t v ~u v g v h v ~c v m v ~pp , 
~p v ~q v ~s v t v ~u v g v h v ~c v ~m v pp , ~p v ~q v ~s v t v ~u v g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v g v ~h v c v m v pp , ~p v ~q v ~s v t v ~u v g v ~h v c v m v ~pp , 
~p v ~q v ~s v t v ~u v g v ~h v c v ~m v pp , ~p v ~q v ~s v t v ~u v g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v g v ~h v ~c v m v pp , ~p v ~q v ~s v t v ~u v g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v t v ~u v g v ~h v ~c v ~m v pp , ~p v ~q v ~s v t v ~u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v h v c v m v pp , ~p v ~q v ~s v t v ~u v ~g v h v c v m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v h v c v ~m v pp , ~p v ~q v ~s v t v ~u v ~g v h v c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v h v ~c v m v pp , ~p v ~q v ~s v t v ~u v ~g v h v ~c v m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v h v ~c v ~m v pp , ~p v ~q v ~s v t v ~u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v ~h v c v m v pp , ~p v ~q v ~s v t v ~u v ~g v ~h v c v m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v ~h v c v ~m v pp , ~p v ~q v ~s v t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v ~h v ~c v m v pp , ~p v ~q v ~s v t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v t v ~u v ~g v ~h v ~c v ~m v pp , ~p v ~q v ~s v t v ~u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v g v h v c v m v pp , ~p v ~q v ~s v ~t v u v g v h v c v m v ~pp , 
~p v ~q v ~s v ~t v u v g v h v c v ~m v pp , ~p v ~q v ~s v ~t v u v g v h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v g v h v ~c v m v pp , ~p v ~q v ~s v ~t v u v g v h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v u v g v h v ~c v ~m v pp , ~p v ~q v ~s v ~t v u v g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v g v ~h v c v m v pp , ~p v ~q v ~s v ~t v u v g v ~h v c v m v ~pp , 
~p v ~q v ~s v ~t v u v g v ~h v c v ~m v pp , ~p v ~q v ~s v ~t v u v g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v g v ~h v ~c v m v pp , ~p v ~q v ~s v ~t v u v g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v u v g v ~h v ~c v ~m v pp , ~p v ~q v ~s v ~t v u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v h v c v m v pp , ~p v ~q v ~s v ~t v u v ~g v h v c v m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v h v c v ~m v pp , ~p v ~q v ~s v ~t v u v ~g v h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v h v ~c v m v pp , ~p v ~q v ~s v ~t v u v ~g v h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v h v ~c v ~m v pp , ~p v ~q v ~s v ~t v u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v ~h v c v m v pp , ~p v ~q v ~s v ~t v u v ~g v ~h v c v m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v ~h v c v ~m v pp , ~p v ~q v ~s v ~t v u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v ~h v ~c v m v pp , ~p v ~q v ~s v ~t v u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v u v ~g v ~h v ~c v ~m v pp , ~p v ~q v ~s v ~t v u v ~g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v h v c v m v pp , ~p v ~q v ~s v ~t v ~u v g v h v c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v h v c v ~m v pp , ~p v ~q v ~s v ~t v ~u v g v h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v h v ~c v m v pp , ~p v ~q v ~s v ~t v ~u v g v h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v h v ~c v ~m v pp , ~p v ~q v ~s v ~t v ~u v g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v ~h v c v m v pp , ~p v ~q v ~s v ~t v ~u v g v ~h v c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v ~h v c v ~m v pp , ~p v ~q v ~s v ~t v ~u v g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v ~h v ~c v m v pp , ~p v ~q v ~s v ~t v ~u v g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v g v ~h v ~c v ~m v pp , ~p v ~q v ~s v ~t v ~u v g v ~h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v h v c v m v pp , ~p v ~q v ~s v ~t v ~u v ~g v h v c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v h v c v ~m v pp , ~p v ~q v ~s v ~t v ~u v ~g v h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v h v ~c v m v pp , ~p v ~q v ~s v ~t v ~u v ~g v h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v h v ~c v ~m v pp , ~p v ~q v ~s v ~t v ~u v ~g v h v ~c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v c v m v pp , ~p v ~q v ~s v ~t v ~u v ~g v ~h v c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v c v ~m v pp , ~p v ~q v ~s v ~t v ~u v ~g v ~h v c v ~m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v m v pp , ~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v m v ~pp , 
~p v ~q v ~s v ~t v ~u v ~g v ~h v ~c v ~m v pp , ~p v ~q v ~s v ~t v u v ~g v ~h v ~c v ~m v ~pp
],sat).





